#!/bin/sh
# Usage: $0 <warn> <crit>

# File to look at:
FILE="/var/TCMon/TCMon_Perf.mon"

# Message string
MSGSTR="TrakCare components running slow:"
UNKSTR="Could not get TrakCare component performance data."

# Line number, CR delimited
LINE=2
# Column number, ^ delimited
COLN=1

# Thresholds for warning and critical:
WARN=$1
CRIT=$2

cat $FILE | awk -F^ 'NR==line { f=1;
    	if ($col >= crit) { 
		print "CRITICAL:", msgstr, $col;
        	exit 2;
    	} else if ($col >= warn) {
        	print "WARNING:", msgstr, $col;
        	exit 1;
    	} else if ($col < warn) {
        	print "OK:", msgstr, $col;
        	exit 0;
    	} else {
        	print "UNKNOWN:", unkstr;
        	exit 3;
	}
    } END { 
	if (!f) {
	    print "UNKNOWN:", unkstr; 
	    exit 3; 
	}
    }' line=$LINE col=$COLN crit=$CRIT warn=$WARN msgstr="$MSGSTR" unkstr="$UNKSTR"
exit $?
