#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
#  vpnCLDC.sh
#  
#  Copyright 2016 Carlos "casep" Sepulveda <casep@fedoraproject.org>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  


### Just to avoid typing

function connect {
	ssh $CLDCVPNIp
}

CLDCVPNIp=$(VBoxManage guestproperty enumerate "CL DC VPN" --patterns "/VirtualBox/GuestInfo/Net/0/V4/IP" | cut -d " " -f4 | cut -d, -f1)
while [ -z $CLDCVPNIp ] 
do
	echo "ssh not ready, waiting"
	sleep 10
done
connect
