#!/bin/sh
# log unexpected output somewhere - comment to disable
#DEBUGLOG=/tmp/snmp-cups.log

# server status - is it running
lpstat -r | grep '^scheduler is running$' | wc -l
# completed
lpstat -W completed -o | wc -l
# not-completed
lpstat -W not-completed -o | wc -l

# count up variables
parsestat() {
	local prt_enabled=0
	local prt_disabled=0
	local prt_st_idle=0
	local prt_st_nowprt=0
	local prt_tsk_ready=0
	local prt_tsk_proc=0
	local prt_tsk_prting=0
	local prt_tsk_paused=0
	local prt_tsk_prtfilesent=0
	local prt_tsk_none=0
	local prt_tsk_connect=0
	local state=0
	while read line; do
		if echo "$line" | grep -q '^printer '; then
			if [ $state = 1 ]; then prt_tsk_none=$(($prt_tsk_none+1)); fi
			state=0
		fi
		case $state in
			0)
				if echo "$line" | grep -q '^printer [^ ]\+ [^\.]\+\. \+enabled since '; then
					prt_enabled=$(($prt_enabled+1))
				elif  echo "$line" | grep -q '^printer [^ ]\+ \+disabled since '; then
					prt_disabled=$(($prt_disabled+1))
				else
					if [ -n "$DEBUGLOG" ]; then
						echo "ERROR - 1: can't parse line: $line" >>$DEBUGLOG
					fi
				fi
				if echo "$line" | grep -q '^printer [^ ]\+ is idle\.'; then
					prt_st_idle=$(($prt_st_idle+1))
				elif echo "$line" | grep -q '^printer [^ ]\+ now printing [^ ]\+\.'; then
					prt_st_nowprt=$(($prt_st_nowprt+1))
				elif echo "$line" | grep -q '^printer [^ ]\+ \+disabled since '; then
					# already taken care of - do something pointless to avoid errors
					nop=1
				else
					if [ -n "$DEBUGLOG" ]; then
						echo "ERROR - 2: can't parse line: $line" >>$DEBUGLOG
					fi
				fi
				state=1
			;;
			1)
				if echo "$line" | grep -q -P '^Ready to print'; then
				prt_tsk_ready=$(($prt_tsk_ready+1))
				elif echo "$line" | grep -q -P '^Processing'; then
					prt_tsk_proc=$(($prt_tsk_proc+1))
				elif echo "$line" | grep -q -P '^Printing'; then
					prt_tsk_prting=$(($prt_tsk_prting+1))
				elif echo "$line" | grep -q -P '^Paused'; then
					prt_tsk_paused=$(($prt_tsk_paused+1))
				elif echo "$line" | grep -q -P '^Print file sent'; then
					prt_tsk_prtfilesent=$(($prt_tsk_prtfilesent+1))
				elif echo "$line" | grep -q -P '^Connecting to printer'; then
					prt_tsk_connect=$(($prt_tsk_connect+1))
				else
					if [ -n "$DEBUGLOG" ]; then
						echo "ERROR - 3: can't parse line: $line" >>$DEBUGLOG
					fi
				fi
				state=0
			;;
		esac
	done
	echo $prt_enabled
	echo $prt_disabled
	echo $prt_st_idle
	echo $prt_st_nowprt
	echo $prt_tsk_ready
	echo $prt_tsk_proc
	echo $prt_tsk_prting
	echo $prt_tsk_paused
	echo $prt_tsk_prtfilesent
	echo $prt_tsk_none
	echo $prt_tsk_connect
}
lpstat -p 2>/dev/null | parsestat



# what about stats from page_log - item 5 (pages) X item 6 (copies) - each line is a job

